config/routes.rb
Tutu::Application.routes.draw do
  resources :estadisticas do
    get :lectores, on: :collection
    get :libros, on: :collection
  end

  resources :prestadores do
    get :activar, on: :member
    get :search, on: :collection
  end

  resources :prestamos do
    get :entregar, on: :member
  end

  resources :lectores do
    get :foto, on: :member
    get :foto_url, on: :member
    post :upload, on: :member
    get :search, on: :collection
    post :credenciales, on: :collection
  end

  resources :libros do
    get :search, on: :collection
    post :etiquetas, on: :collection
  end

  devise_for :usuarios

  root :to => 'libros#index'

end

app/controllers/prestadores_controller.rb
class PrestadoresController < ApplicationController
  # GET /prestadores
  # GET /prestadores.json
  def index
    @prestadores = Prestador.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prestadores }
    end
  end

  # GET /prestadores/1
  # GET /prestadores/1.json
  def show
    @prestador = Prestador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prestador }
    end
  end

  # GET /prestadores/new
  # GET /prestadores/new.json
  def new
    @prestador = Prestador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prestador }
    end
  end

  # GET /prestadores/1/edit
  def edit
    @prestador = Prestador.find(params[:id])
  end

  # POST /prestadores
  # POST /prestadores.json
  def create
    @prestador = Prestador.new(params[:prestador])

    respond_to do |format|
      if @prestador.save
        format.html { redirect_to @prestador, notice: 'Prestador fue guardado correctamente.' }
        format.json { render json: @prestador, status: :created, location: @prestador }
      else
        format.html { render action: "new" }
        format.json { render json: @prestador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prestadores/1
  # PUT /prestadores/1.json
  def update
    @prestador = Prestador.find(params[:id])

    respond_to do |format|
      if @prestador.update_attributes(params[:prestador])
        format.html { redirect_to @prestador, notice: 'Prestador fue guardado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prestador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestadores/1
  # DELETE /prestadores/1.json
  def destroy
    @prestador = Prestador.find(params[:id])
    @prestador.destroy

    respond_to do |format|
      format.html { redirect_to prestadores_url }
      format.json { head :no_content }
    end
  end

  def activar
    @prestador = Prestador.find(params[:id])
    if @prestador
      session[:prestador_id] = @prestador.id
    end
  end

  def search
    @prestadores = Prestador.order('nombre').
      finder(params[:q])#.page(params[:page]).per(params[:per])
    respond_to do |format|
      format.json { render json: @prestadores.to_json}
    end
  end

end

app/helpers/prestadores_helper.rb
module PrestadoresHelper
end

app/views/prestadores/_form.html.haml
= form_for(@prestador) do |f|
  = render 'error_messages', target: @prestador

  .field
    = f.label :nombre
    %br
    = f.text_field :nombre
  .actions
    = f.submit class: 'btn btn-primary'

app/views/prestadores/activar.js.erb
$('#prestador-menu span').text("(<%= @prestador.nombre %>)")

app/views/prestadores/edit.html.haml
%h1 Editar Prestador

= render 'form'

.btn-group
  = link_to 'Mostrar', @prestador, class: 'btn'
  = link_to 'Listado', prestadores_path, class: 'btn'

app/views/prestadores/index.html.haml
%h1 Listado de Prestadores

- if @prestadores.any?
  %table#prestadores.table.table-stripped
    %thead
      %tr
        %th Nombre
        %th

    %tbody
      - @prestadores.each do |prestador|
        %tr
          %td= prestador.nombre
          %td
            .btn-group
              = link_to 'Mostrar', prestador, class: 'btn'
              = link_to 'Editar', edit_prestador_path(prestador), class: 'btn'
              = link_to 'Eliminar', prestador, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger'
- else
  %div
    %h3 No se encontraron Prestadores

%br

= link_to "Nuevo Prestador", new_prestador_path, class: 'btn btn-primary'

app/views/prestadores/new.html.haml
%h1 Agregar nuevo Prestador

= render 'form'

.btn-group
  = link_to 'Listado', prestadores_path

app/views/prestadores/show.html.haml
%p
  %b Nombre:
  = @prestador.nombre

.btn-group
  = link_to 'Editar', edit_prestador_path(@prestador), class: 'btn'
  = link_to 'Listado', prestadores_path, class: 'btn'