config/routes.rb
Tutu::Application.routes.draw do
  resources :estadisticas do
    get :lectores, on: :collection
    get :libros, on: :collection
  end

  resources :prestadores do
    get :activar, on: :member
    get :search, on: :collection
  end

  resources :prestamos do
    get :entregar, on: :member
  end

  resources :lectores do
    get :foto, on: :member
    get :foto_url, on: :member
    post :upload, on: :member
    get :search, on: :collection
    post :credenciales, on: :collection
  end

  resources :libros do
    get :search, on: :collection
    post :etiquetas, on: :collection
  end

  devise_for :usuarios

  root :to => 'libros#index'

end

app/models/prestamo.rb
class Prestamo < ActiveRecord::Base
  attr_accessible :fecha_prestamo, :fecha_entrega, :perdida, :lector_id, :libro_id, :prestador_id
  belongs_to :lector 
  belongs_to :libro
  belongs_to :prestador

  belongs_to :libro_de_texto, class_name: 'Libro', conditions: { libros: {tipo: false} }, foreign_key: 'libro_id'
  belongs_to :juego, class_name: 'Libro', conditions: { libros: {tipo: true} }, foreign_key: 'libro_id'

  scope :no_entregados, where(fecha_entrega: nil)
  scope :entregados, where('fecha_entrega IS NOT NULL')
end

app/controllers/prestamos_controller.rb
# encoding: utf-8
class PrestamosController < ApplicationController
  # GET /prestamos
  # GET /prestamos.json
  def index
    @prestamos = Prestamo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prestamos }
    end
  end

  # GET /prestamos/1
  # GET /prestamos/1.json
  def show
    @prestamo = Prestamo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prestamo }
    end
  end

  # GET /prestamos/new
  # GET /prestamos/new.json
  def new
    @prestamo = Prestamo.new
    @prestamo.prestador = Prestador.find(session[:prestador_id]) if session[:prestador_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prestamo }
    end
  end

  # GET /prestamos/1/edit
  def edit
    @prestamo = Prestamo.find(params[:id])
  end

  # POST /prestamos
  # POST /prestamos.json
  def create
    @prestamo = Prestamo.new(params[:prestamo])

    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to prestamos_path, notice: 'Prestamo se guardó correctamente.' }
        format.json { render json: @prestamo, status: :created, location: @prestamo }
      else
        format.html { render action: "new" }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prestamos/1
  # PUT /prestamos/1.json
  def update
    @prestamo = Prestamo.find(params[:id])

    respond_to do |format|
      if @prestamo.update_attributes(params[:prestamo])
        format.html { redirect_to @prestamo, notice: 'Prestamo se modificó correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1
  # DELETE /prestamos/1.json
  def destroy
    @prestamo = Prestamo.find(params[:id])
    @prestamo.destroy

    respond_to do |format|
      format.html { redirect_to prestamos_url }
      format.json { head :no_content }
    end
  end


  def entregar
    @prestamo = Prestamo.find(params[:id])
  end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_entrega.html.haml
= form_for(@prestamo, html: { class: 'form-horizontal'}) do |f|
  = render 'error_messages', target: @prestamo

  .control-group
    = f.label :fecha_entrega,  class: 'control-label'
    .controls
      = f.text_field :fecha_entrega

  .control-group
    = f.label :perdida,  class: 'control-label'
    .controls
      = f.check_box :perdida

  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/prestamos/_form.html.haml
= form_for(@prestamo, html: { class: 'form-horizontal'}) do |f|
  = render 'error_messages', target: @prestamo

  .control-group
    = f.label :libro_id, 'Libro', class: 'control-label'
    .controls
      = f.hidden_field :libro_id, class: 'select2 multi ajax span5', data: { source: search_libros_path, multiple: true }, multiple: true
      = @prestamo.libro.titulo if @prestamo.libro
  .control-group
    = f.label :lector_id, 'Lector', class: 'control-label'
    .controls
      = f.hidden_field :lector_id, class: 'select2 ajax span2', data: { source: search_lectores_path }
      = @prestamo.lector.nombre_completo if @prestamo.libro
  .control-group
    = f.label :prestador_id, 'Prestador', class: 'control-label'
    .controls
      = f.hidden_field :prestador_id, class: 'select2 ajax span2', data: { source: search_prestadores_path }
      = @prestamo.prestador.nombre if @prestamo.prestador

  .control-group
    = f.label :fecha_prestamo,  class: 'control-label'
    .controls
      = f.text_field :fecha_prestamo

  .control-group
    = f.label :fecha_entrega,  class: 'control-label'
    .controls
      = f.text_field :fecha_entrega

  .control-group
    = f.label :perdida,  class: 'control-label'
    .controls
      = f.text_field :perdida

  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/prestamos/edit.html.haml
%h1 Editar Préstamo

= render 'form'

.btn-group
  = link_to 'Mostrar', @prestamo, class: 'btn'
  = link_to 'Listado', prestamos_path, class: 'btn'

app/views/prestamos/entregar.html.haml
= render 'entrega'

app/views/prestamos/index.html.haml
%h1 Listado de Prestamos

%table#prestamos.table.table-stripped
  %thead
    %tr
      %th Título del libro
      %th Lector 
      %th
      %th
      %th

  %tbody
    - @prestamos.each do |prestamo|
      %tr
        %td= prestamo.libro.titulo

        %td= prestamo.lector.nombre_completo
        %td
          .btn-group
            = link_to 'Mostrar', prestamo, class: 'btn' 
            = link_to 'Editar', edit_prestamo_path(prestamo), class: 'btn'
            = link_to 'Eliminar', prestamo, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger'

.form-actions
  = link_to "Nuevo Prestamo", new_prestamo_path, class: 'btn btn-primary'

app/views/prestamos/new.html.haml
%h1 Nuevo préstamo 

= render 'form'

.btn-group
  = link_to 'Listado', prestamos_path, class: 'btn'

app/views/prestamos/show.html.haml
%h1
  = "#{@prestamo.lector.nombre_completo}"
  
%h2 
  = "#{@prestamo.libro.titulo}"

- if @prestamo.prestador
  %h3
    %b Prestó:
    = @prestamo.prestador.nombre

.form-actions
  .btn-group
    = link_to 'Editar', edit_prestamo_path(@prestamo), class: 'btn'
    = link_to 'Listado', prestamos_path, class: 'btn'