config/routes.rb
Tutu::Application.routes.draw do
  resources :estadisticas do
    get :lectores, on: :collection
    get :libros, on: :collection
  end

  resources :prestadores do
    get :activar, on: :member
    get :search, on: :collection
  end

  resources :prestamos do
    get :entregar, on: :member
  end

  resources :lectores do
    get :foto, on: :member
    get :foto_url, on: :member
    post :upload, on: :member
    get :search, on: :collection
    post :credenciales, on: :collection
  end

  resources :libros do
    get :search, on: :collection
    post :etiquetas, on: :collection
  end

  devise_for :usuarios

  root :to => 'libros#index'

end

app/models/libro.rb
require 'rqrcode' 
require 'rqrcode/export/png'

class Libro < ActiveRecord::Base
  attr_accessible :autor, :editorial, :isbn, :titulo, :paginas, :descripcion, :cantidad, :tipo, :qr
  has_many :prestamos
  has_many :lectores, through: :prestamos

  validates :titulo, presence: true
  validates :autor, presence: true

  validates :isbn, length: { minimum: 2, maximum: 14 } 

  scope :libros, where(tipo: false)
  scope :libros, where(tipo: true)


  mount_uploader :qr, CodigoUploader

  after_create :generar_codigo

  scope :finder, lambda { |q| where("titulo like :q or autor like :q or descripcion like :q or isbn like :q or codigo like :q", q: "%#{q}%") } 

  #Para estadísticas
  #
  scope :mas_prestados,
    joins(:prestamos).
    select('libros.*, COUNT(prestamos.id) as prestados').
    group('libros.id').
    order('prestados DESC')

  scope :mas_prestados_libros,
    joins(:prestamos).
    select('libros.*, COUNT(prestamos.id) as prestados').
    group('libros.id').
    order('prestados DESC').
    where(tipo: false)

  scope :mas_prestados_juegos,
    joins(:prestamos).
    select('libros.*, COUNT(prestamos.id) as prestados').
    group('libros.id').
    order('prestados DESC').
    where(tipo: true)

  def self.mas_prestados_grafica(tipo= '', limit= 0)
    case tipo.downcase 
    when 'libros'
      libros = Libro.mas_prestados_libros
    when 'juegos'
      libros = Libro.mas_prestados_juegos
    else
      libros = Libro.mas_prestados
    end

    if limit > 0
      libros.limit(limit)
    else
      libros.all
    end
    libros.map do |l| 
      {
        label: l.titulo,
        value: l.prestados
      } 
    end
  end


private 
  def generar_codigo
      self.codigo = "U48M%05d" % self.id  
      temp_qr = RQRCode::QRCode.new(codigo.to_s, size: 2, level: :l).as_png
      temp_file_name = File.join(Rails.root, 'tmp', (0...8).map{(65+rand(26)).chr}.join )
      temp_file = temp_qr.save(temp_file_name)
      self.qr = File.open(temp_file_name)
      self.save!(validate: false)
  end

  
  def as_json(options)
    { id: id, text: titulo }
  end 
  
  def as_json(options)
    { id: id, text: titulo }
  end 
end

app/controllers/libros_controller.rb
# encoding: utf-8
class LibrosController < ApplicationController
  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libros }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    @libro = Libro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
    @libro = Libro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/1/edit
  def edit
    @libro = Libro.find(params[:id])
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(params[:libro])

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render json: @libro, status: :created, location: @libro }
      else
        format.html { render action: "new" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libros/1
  # PUT /libros/1.json
  def update
    @libro = Libro.find(params[:id])

    respond_to do |format|
      if @libro.update_attributes(params[:libro])
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro = Libro.find(params[:id])
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :no_content }
    end
  end

 def search
   @libros = Libro.order('titulo').
      finder(params[:q])#.page(params[:page]).per(params[:per])
    respond_to do |format|
      format.json { render json: @libros.to_json}
    end
  end

  def etiquetas 
    if params[:libros_ids].blank? or params[:libros_ids].empty?
      redirect_to( libros_path, alert: 'No ha seleccionado ningún Libro' )
    else
      @libros = Libro.find(params[:libros_ids])
      @una_etiqueta = params[:una_por_libro] ? true : false
    end
  end

end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_etiqueta.html.haml
.etiqueta
  .qr
    = image_tag l.qr_url
  .datos
    %p
      %strong= l.titulo 
    %p
      %strong Autor
      = l.autor
    - unless l.tipo
      %p
        %strong ISBN
        = l.isbn

app/views/libros/_form.html.haml
= form_for @libro,html:{ class: 'form-horizontal'} do |f|
  = render 'error_messages', target: @libro

  .control-group
    = f.label :titulo, class: 'control-label'
    .controls
      = f.text_field :titulo
  .control-group
    = f.label :autor, class: 'control-label'
    .controls
      = f.text_field :autor
  .control-group
    = f.label :editorial, class: 'control-label'
    .controls
      = f.text_field :editorial
  .control-group
    = f.label :isbn, class: 'control-label'
    .controls
      = f.text_field :isbn
  .control-group
    = f.label :tipo, "¿Es juego?", class: 'control-label'
    .controls
      = f.check_box :tipo
  .control-group
    = f.label :descripcion, class: 'control-label'
    .controls
      = f.text_area :descripcion
  .control-group
    = f.label :cantidad, class: 'control-label'
    .controls
      = f.text_field :cantidad


  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/libros/edit.html.haml
%h1 Modificar datos del Libro

= render 'form'

.btn-group
  = link_to 'Mostrar', @libro, class: 'btn'
  = link_to 'Listado', libros_path, class: 'btn'

app/views/libros/etiquetas.html.haml
- @libros.each do |l|
  - (@una_etiqueta ? 1 : l.cantidad) .times do 
    = render 'etiqueta', l: l

app/views/libros/index.html.haml
= form_tag action: :etiquetas do
  .row-fluid
    .span6
      %h1 Libros
    .span6
      .span6  
        = check_box_tag :una_por_libro, class: 'left'
        = label_tag :una_por_libro, "¿Una etiqueta por libro?"
      .span6
        = submit_tag "Generar Etiquetas", class: 'btn btn-warning' 

  %table#libros.table.table-stripped
    %thead
      %tr
        %th= check_box_tag "libros_select_all"
        %th Titulo
        %th Autor
        %th Editorial
        %th Isbn
        %th
    %tbody
      - @libros.each do |libro|
        %tr
          %td= check_box_tag 'libros_ids[]', libro.id
          %td= libro.titulo
          %td= libro.autor
          %td= libro.editorial
          %td= libro.isbn
          %td
            .btn-group
              = link_to 'Mostrar', libro, class: 'btn'
              = link_to 'Editar', edit_libro_path(libro), class: 'btn'
              = link_to 'Eliminar', libro, method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger'

.form-actions
  = link_to "Nuevo Libro", new_libro_path, class: 'btn btn-primary'

app/views/libros/new.html.haml
%h1 Agregar nuevo Libro

= render 'form'

.btn-group
  = link_to 'Listado', libros_path, class: 'btn'

app/views/libros/show.html.haml
= render 'etiqueta', l: @libro
.row-fluid
  .span6
    %h1
      = @libro.titulo

    %h2
      = @libro.autor

    %p
      %b Editorial:
      = @libro.editorial

    %p
      %b Isbn:
      = @libro.isbn

    %h1
      = @libro.cantidad
  .span6
    = image_tag @libro.qr_url, class: 'img-polaroid' 
.form-actions
  .btn-group
    = link_to 'Editar', edit_libro_path(@libro), class: 'btn'
    = link_to 'Listado', libros_path, class: 'btn'