config/routes.rb
Tutu::Application.routes.draw do
  resources :estadisticas do
    get :lectores, on: :collection
    get :libros, on: :collection
  end

  resources :prestadores do
    get :activar, on: :member
    get :search, on: :collection
  end

  resources :prestamos do
    get :entregar, on: :member
  end

  resources :lectores do
    get :foto, on: :member
    get :foto_url, on: :member
    post :upload, on: :member
    get :search, on: :collection
    post :credenciales, on: :collection
  end

  resources :libros do
    get :search, on: :collection
    post :etiquetas, on: :collection
  end

  devise_for :usuarios

  root :to => 'libros#index'

end

app/controllers/estadisticas_controller.rb
class EstadisticasController < ApplicationController

  def index
    @total_prestados = Prestamo.count
    @total_en_prestamo = Prestamo.includes(:libros_de_texto).where('fecha_entrega IS NOT NULL').count
    @total_libros_prestados = Prestamo.joins(:libro_de_texto).where('fecha_entrega IS NOT NULL').count
    @total_juegos_prestados = Prestamo.joins(:juego).where('fecha_entrega IS NOT NULL').count
  end

  def lectores
    @lectores = Lector.mas_frecuentes.all
  end 

  def libros
    @libros= Libro.mas_prestados.all
  end 

end

app/helpers/estadisticas_helper.rb
module EstadisticasHelper
end

app/views/estadisticas/index.html.haml
%h1 Libros Prestados 
.row-fluid
  .span-3
    %h2
      Total:
      = @total_prestados
  .span-3
    %h2
      En préstamo:
      = @total_en_prestamo
  .span-3
    %h2
      Libros en prestamo:  
      = @total_libros_prestados
  .span-3
    %h2
      Juegos en prestamo:  
      = @total_juegos_prestados
%h2
  = link_to 'Lectores', lectores_estadisticas_path
.row
  .span-6
    %h2 Total
    #lectores_frecuentes_chart{ data: { lectores: Lector.mas_prestamos_grafica('', 10).to_json }}
  .span-6
    %h2 Libros
    #lectores_frecuentes_libros_chart{ data: { lectores: Lector.mas_prestamos_grafica('libros',10).to_json }}
  .span-6
    %h2 Juegos    
    #lectores_frecuentes_juegos_chart{ data: { lectores: Lector.mas_prestamos_grafica('juegos', 10).to_json }}

%h2
  = link_to 'Libros', libros_estadisticas_path
.row
  .span-6
    %h2 Total
    #libros_frecuentes_chart{ data: { libros: Libro.mas_prestados_grafica('', 10).to_json }}
  .span-6
    %h2 Libros
    #libros_frecuentes_libros_chart{ data: { libros: Libro.mas_prestados_grafica('libros',10).to_json }}
  .span-6
    %h2 Juegos    
    #libros_frecuentes_juegos_chart{ data: { libros: Libro.mas_prestados_grafica('juegos', 10).to_json }}

app/views/estadisticas/lectores.html.haml
%h1 Lectores
.row
  .span-6
    %h2 Total
    #lectores_frecuentes_chart{ data: { lectores: Lector.mas_prestamos_grafica('', 10).to_json }}
  .span-6
    %h2 Libros
    #lectores_frecuentes_libros_chart{ data: { lectores: Lector.mas_prestamos_grafica('libros',10).to_json }}
  .span-6
    %h2 Juegos    
    #lectores_frecuentes_juegos_chart{ data: { lectores: Lector.mas_prestamos_grafica('juegos', 10).to_json }}

%table.table.table-striped
  %thead
    %tr
      %th Nombre 
      %th Grado/Grupo 
      %th Libros
      %th Juegos
      %th Total

  %tbody
    - @lectores.each do |l|
      %tr
        %td= link_to l.nombre_completo, libro_path(l)
        %td= "#{l.grado} #{l.grupo}" 
        %td= l.libros_de_texto.count
        %td= l.juegos.count
        %td= l.libros.count

app/views/estadisticas/libros.html.haml
%h1 Libros
.row-fluid
  .span6
    %h2 Total
    #libros_frecuentes_chart{ data: { libros: Libro.mas_prestados_grafica('', 10).to_json }}
  .span6
    %h2 Libros
    #libros_frecuentes_libros_chart{ data: { libros: Libro.mas_prestados_grafica('libros',10).to_json }}
  .span6
    %h2 Juegos    
    #libros_frecuentes_juegos_chart{ data: { libros: Libro.mas_prestados_grafica('juegos', 10).to_json }}

%table.table.table-striped
  %thead
    %tr
      %th Titulo 
      %th Tipo
      %th Total

  %tbody
    - @libros.each do |l|
      %tr
        %td= link_to l.titulo, libro_path(l)
        %td= l.tipo ? "Juego" : "Libro"
        %td= l.prestados